/**
 * @filename    TGON.h
 * @author      ggomdyu
 * @since       05/27/2018
 */

#pragma once

#define TGON_USING_OPENGL 1
#include "Core/Audio/AudioBuffer.h"
#include "Core/Audio/AudioPlayer.h"
#include "Core/Debug/Log.h"
#include "Core/Drawing/Image.h"
#include "Core/Platform/Window.h"
#include "Core/Platform/WindowType.h"
#include "Core/Platform/Application.h"
#include "Core/Platform/Screen.h"
#include "Core/Platform/Locale.h"
#include "Core/Platform/ScreenType.h"
#include "Core/Time/Time.h"
#include "Core/Utility/StaticInvoke.h"
#include "Core/Hardware/InputManager.h"
#include "Core/Hardware/Keyboard.h"
#include "Core/Hardware/KeyboardType.h"
#include "Core/Hardware/Mouse.h"
#include "Core/Hardware/MouseType.h"
#include "Core/Object/Object.h"
#include "Core/Object/Module/TimeModule.h"
#include "Core/Object/Module/TaskModule.h"
#include "Core/Object/Module/InputModule.h"
#include "Core/Object/IRuntimeObjectUtility.h"
#include "Core/Object/Engine.h"
#include "Core/File/Path.h"
#include "Core/Random/Random.h"
#include "Core/String/StringViewHash.h"
#include "Core/String/FixedString.h"
#include "Core/String/FixedStringUtility.h"
#include "Core/File/Path.h"
#include "Core/Math/Mathematics.h"
#include "Core/Math/Vector3.h"
#include "Core/Math/Vector2.h"
#include "Core/Math/Color.h"
#include "Core/Math/Matrix4x4.h"
#include "Core/Math/Extent.h"
#include "Core/Hash/UUID.h"
#include "Core/Hash/Hash.h"
#include "Core/Random/Random.h"
#include "Core/File/Path.h"
#include "Core/Utility/RAII.h"
#include "Core/Utility/Stopwatch.h"
#include "Core/Utility/Algorithm.h"
#include "Core/Utility/AutoCast.h"
#include "Core/Utility/InstanceCounter.h"
#include "Core/Utility/InstantiateCounter.h"
#include "Graphics/LowLevel/Generic/GenericGraphics.h"
#include "Graphics/LowLevel/Texture.h"
#include "Graphics/LowLevel/OpenGL/OpenGLShader.h"
#include "Graphics/LowLevel/OpenGL/OpenGLShaderCode.h"
#include "Graphics/Render/Renderer.h"
#include "Graphics/Render/MeshUtility.h"
#include "Graphics/LowLevel/VertexBuffer.h"
#include "Graphics/LowLevel/IndexBuffer.h"
#include "Graphics/Render/FVF.h"
#include "Graphics/Object/Module/GraphicsModule.h"
#include "Game/Object/GameObject.h"
#include "Game/Component/Component.h"
#include "Game/Component/SpriteComponent.h"
#include "Graphics/Render/Camera.h"
