#pragma once

#define TGON_PLATFORM_NAME MacOS
#define TGON_PLATFORM_MACOS 1
#define TGON_GRAPHICS_OPENGL 1
#define TGON_USING_LITTLE_ENDIAN 1
#define TGON_SUPPORT_SSE
#define TGON_SUPPORT_SSE2
#define TGON_SUPPORT_SIMD TGON_SUPPORT_SSE || TGON_SUPPORT_SSE2
#define TGON_USING_SIMD TGON_SUPPORT_SIMD
