/*
* Author : Junho-Cha
* Date : 05/08/2016
* Latest author :
* Latest date :
*/

#pragma once
#include <d3d9.h>

namespace tgon
{


enum class D3d9ErrorCode
{
	kSuccess = S_OK,
	kFailed = S_FALSE,
	kOutOfVideoMemory = D3DERR_OUTOFVIDEOMEMORY,
	kWrongTextureFormat = D3DERR_WRONGTEXTUREFORMAT,
	kNotFound = D3DERR_NOTFOUND,
	kInvalidCall = D3DERR_INVALIDCALL,
	kInvalidDevice = D3DERR_INVALIDDEVICE,
	kDeviceLost = D3DERR_DEVICELOST,
	kDeviceRemoved = D3DERR_DEVICEREMOVED,
};
//
//#define D3DERR_UNSUPPORTEDCOLOROPERATION        MAKE_D3DHRESULT(2073)
//#define D3DERR_UNSUPPORTEDCOLORARG              MAKE_D3DHRESULT(2074)
//#define D3DERR_UNSUPPORTEDALPHAOPERATION        MAKE_D3DHRESULT(2075)
//#define D3DERR_UNSUPPORTEDALPHAARG              MAKE_D3DHRESULT(2076)
//#define D3DERR_TOOMANYOPERATIONS                MAKE_D3DHRESULT(2077)
//#define D3DERR_CONFLICTINGTEXTUREFILTER         MAKE_D3DHRESULT(2078)
//#define D3DERR_UNSUPPORTEDFACTORVALUE           MAKE_D3DHRESULT(2079)
//#define D3DERR_CONFLICTINGRENDERSTATE           MAKE_D3DHRESULT(2081)
//#define D3DERR_UNSUPPORTEDTEXTUREFILTER         MAKE_D3DHRESULT(2082)
//#define D3DERR_CONFLICTINGTEXTUREPALETTE        MAKE_D3DHRESULT(2086)
//#define D3DERR_DRIVERINTERNALERROR              MAKE_D3DHRESULT(2087)
//#define D3DERR_MOREDATA                         MAKE_D3DHRESULT(2151)
//#define D3DERR_DEVICENOTRESET                   MAKE_D3DHRESULT(2153)
//#define D3DERR_NOTAVAILABLE                     MAKE_D3DHRESULT(2154)
//#define D3DERR_OUTOFVIDEOMEMORY                 MAKE_D3DHRESULT(380)
//#define D3DERR_DRIVERINVALIDCALL                MAKE_D3DHRESULT(2157)
//#define D3DERR_WASSTILLDRAWING                  MAKE_D3DHRESULT(540)
//#define D3DERR_DEVICEHUNG                       MAKE_D3DHRESULT(2164)
//#define D3DERR_UNSUPPORTEDOVERLAY               MAKE_D3DHRESULT(2171)
//#define D3DERR_UNSUPPORTEDOVERLAYFORMAT         MAKE_D3DHRESULT(2172)
//#define D3DERR_CANNOTPROTECTCONTENT             MAKE_D3DHRESULT(2173)
//#define D3DERR_UNSUPPORTEDCRYPTO                MAKE_D3DHRESULT(2174)
//#define D3DERR_PRESENT_STATISTICS_DISJOINT      MAKE_D3DHRESULT(2180)



}