#pragma once
#include <cstdint>
#include <cassert>
#include <memory>
#include <string>
#include <vector>
#include <map>
#include <unordered_map>
#include <fmt/format.h>
#include <AL/al.h>
#include <AL/alc.h>
